name: ShadyBusiness
version: '${project.version}'
main: me.pm7.shady_business.ShadyBusiness
api-version: '1.21'
commands:
  start:
    description: "UwU~"
    usage: /<command>
  endsession:
    description: "OwO what's this?"
  info:
    description: ">//w//<"
  givelife:
    description: "^w^"
  test:
    description: tests whatever the current test is. Should not ever be run.