name: ShadyBusiness
version: '1.0'
main: me.pm7.shady_business.ShadyBusiness
api-version: '1.21'
commands:
  startsession:
    description: "Starts the session and gives roles after a few minutes"
    usage: /<command>
  endsession:
    description: "Stops the session, dealing with failed roles"
  givelife:
    description: "Gives a life to a player"
    usage: /<command> <player>
  cure:
    description: "manually cure a boogeyman if they get a kill that isn't credited"
    usage: /<command>
  startvote:
    description: "Begins the condemned vote"
    usage: /<command>
  info:
    description: "gets info about your current role"
    usage: /<command>
  votemenu:
    description: "not necessary to run, this is the command that clicking the chat thingy does"
    usage: /<command>
  setlife:
    description: "sets the life count of a specific player"
    usage: /<command> <player> <integer>
  test:
    description: "o3o"
    usage: /<command>