name: ShadyBusiness
version: '1.0-SNAPSHOT'
main: me.pm7.shady_business.ShadyBusiness
api-version: '1.21'
commands:
  start:
    description: "UwU~"
    usage: /<command>
  endsession:
    description: "OwO what's this?"
  info:
    description: "returns info about the role of the player that ran the command."
    usage: /<command>
  givelife:
    description: "^w^"
    usage: /<command>
  setlife:
    description: "only for admins. sets the life count of a player"
    usage: /<command> <player> <integer>
  test:
    description: "tests whatever the current test is. Should not ever be run."
  startvote:
    description: ">//w//<"
    usage: /<command>
  votemenu:
    description: "for if somebody accidentally clears their chat"
    usage: /<command>