name: ShadyBusiness
version: '1.0-SNAPSHOT'
main: me.pm7.shady_business.ShadyBusiness
api-version: '1.21'
commands:
  startsession:
    description: "UwU~"
    usage: /<command>
  endsession:
    description: "OwO what's this?"
  givelife:
    description: "^w^"
    usage: /<command>
  cure:
    description: "nya :3"
    usage: /<command>
  startvote:
    description: ">//w//<"
    usage: /<command>
  info:
    description: "qwq"
    usage: /<command>
  votemenu:
    description: "Piffin is the only person that has to use this command"
    usage: /<command>
  setlife:
    description: "bwomp"
    usage: /<command> <player> <integer>
  test:
    description: "o3o"
    usage: /<command>